# Generated by Django 4.2.8 on 2024-02-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_persistent', models.CharField(blank=True, db_index=True, help_text='Поле сохраняется даже если объект пользователя удален', max_length=200, null=True, verbose_name='Имя пользователя')),
                ('requested_at', models.DateTimeField(db_index=True, verbose_name='Дата и время запроса')),
                ('response_ms', models.PositiveIntegerField(default=0, verbose_name='Время выполнения кода представления, мс')),
                ('path', models.CharField(db_index=True, max_length=200, verbose_name='URL запроса')),
                ('view', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='View запроса')),
                ('view_method', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='View-метод запроса')),
                ('remote_addr', models.GenericIPAddressField(db_index=True, verbose_name='IP-адрес источника запроса')),
                ('host', models.URLField(db_index=True, verbose_name='Хост')),
                ('method', models.CharField(db_index=True, max_length=10, verbose_name='Метод запроса')),
                ('query_params', models.TextField(blank=True, null=True, verbose_name='Параметры запроса')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Данные')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Ошибки')),
                ('status_code', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Статус ответа')),
            ],
            options={
                'verbose_name': 'Лог запроса к DRF API',
                'verbose_name_plural': 'Логи запросов к DRF API',
            },
        ),
    ]
