# Generated by Django 4.2.8 on 2024-02-22 16:04

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drf_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(django.db.models.functions.text.Upper('username_persistent'), name='username_persistent_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username_persistent'], name='username_persistent_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('username_persistent'), name='gin_trgm_ops'), name='username_persistent_up_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(django.db.models.functions.text.Upper('path'), name='path_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['path'], name='path_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('path'), name='gin_trgm_ops'), name='path_up_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(django.db.models.functions.text.Upper('view'), name='view_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['view'], name='view_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('view'), name='gin_trgm_ops'), name='view_upper_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(django.db.models.functions.text.Upper('view_method'), name='view_method_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['view_method'], name='view_method_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('view_method'), name='gin_trgm_ops'), name='view_method_upper_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(django.db.models.functions.text.Upper('host'), name='host_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['host'], name='host_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('host'), name='gin_trgm_ops'), name='host_upper_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(django.db.models.functions.text.Upper('method'), name='method_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['method'], name='method_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('method'), name='gin_trgm_ops'), name='method_upper_gin_idx'),
        ),
    ]
