FROM node:20.13-alpine

ARG NPM_TOKEN
ENV NPM_TOKEN=$NPM_TOKEN
ARG NPM_REGISTRY
ENV NPM_REGISTRY=$NPM_REGISTRY

WORKDIR /app
COPY package.json package-lock.json .npmrc /app/
RUN npm set "//$NPM_REGISTRY/:_authToken=$NPM_TOKEN"
RUN apk add --no-cache --virtual build-deps make gcc g++ python3 && npm ci --omit=dev && apk del --no-cache build-deps
