version: '3.7'

services:
  nginx:
    volumes:
      - ${TLS_CERTIFICATE}:/etc/nginx/certs/cert.pem
      - ${TLS_CERTIFICATE_KEY}:/etc/nginx/certs/key.pem

  backend:
    restart: unless-stopped
    volumes:
      - ./backend/:/app/:cached
      - static:/app/static/:delegated
    entrypoint: ./entrypoint.sh
    command: poetry run python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000

  db:
    restart: unless-stopped
    ports:
      - 15239:5432

  redis:
    ports:
      - 6379:6379

volumes:
  static:
  redisdata:
  postgresdata:
  nginx_cache:
  api_cache:
