version: '3.8'

services:
  backend:
    restart: unless-stopped
    volumes:
      - ./backend/:/app/:cached
      - static:/app/static/:delegated
    entrypoint: ./entrypoint.sh
    command: poetry run python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000

  db:
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 15239:5432

  redis:
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379

volumes:
  redisdata:
  postgresdata:
  static:
  nginx_cache:
  api_cache:
