version: '3.7'

services:

  frontend:
    image: registry.gitlab.idacloud.ru/idaproject/gals/frontend:${TAG:-latest}
    restart: always
    build:
      context: ./frontend
      cache_from: [ "registry.gitlab.idacloud.ru/idaproject/gals/frontend:${CACHE_FROM_TAG:-latest}" ]
      args:
        - PACKAGES_IMAGE=${NPM_PACKAGES}
        - UI_DEMO=${UI_DEMO}
        - SERVER_API_URL=http://backend:8000
        - IMGPROXY_SITE_HOST=${IMGPROXY_SITE_HOST}
        - REDIS_DSN=${REDIS_DSN}
        - SENTRY_DSN_FRONTEND=${SENTRY_DSN_FRONTEND}
        - SENTRY_ENVIRONMENT=${CI_COMMIT_REF_SLUG:-production}
        - SENTRY_RELEASE=${CI_PIPELINE_ID}
        - YND_CAPTCHA_CLIENT_KEY=${YND_CAPTCHA_CLIENT_KEY}
    command: npm run start
    entrypoint: ./entrypoint.production.sh
    environment:
      - IMGPROXY_SITE_HOST
      - UI_DEMO
      - SERVER_API_URL=http://backend:8000
      - REDIS_DSN
      - SENTRY_DSN_FRONTEND
      - SENTRY_ENVIRONMENT=${CI_COMMIT_REF_SLUG:-production}
      - SENTRY_RELEASE=${CI_PIPELINE_ID}
      - YND_CAPTCHA_CLIENT_KEY=${YND_CAPTCHA_CLIENT_KEY}
    depends_on:
      - backend
    volumes:
      - nuxt:/app/nuxt_volume:delegated
