build:backend:
  stage: build
  script:
    - TAG=${CI_COMMIT_REF_SLUG} docker compose -f docker-compose.yml -f docker-compose.production.yml pull backend || true
    - TAG=${CI_COMMIT_SHA} CACHE_FROM_TAG=${CI_COMMIT_REF_SLUG} docker compose -f docker-compose.yml -f docker-compose.production.yml build backend
    - TAG=${CI_COMMIT_SHA} docker compose -f docker-compose.yml -f docker-compose.production.yml push backend
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/
      changes:
        - backend/**/*
        - gitlab/build.yml
        - .gitlab-ci.yml
        - docker-compose.yml
        - docker-compose.production.yml

build:frontend:
  stage: build
  script:
    - TAG=${CI_COMMIT_REF_SLUG} docker compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.frontend.yml pull frontend || true
    - TAG=${CI_COMMIT_SHA} CACHE_FROM_TAG=${CI_COMMIT_REF_NAME} docker compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.frontend.yml build frontend
    - TAG=${CI_COMMIT_SHA} docker compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.frontend.yml push frontend
    - env
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: ${ENVIRONMENT_URL}
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/
      changes:
        - frontend/**/*
        - gitlab/build.yml
        - .gitlab-ci.yml
        - docker-compose.yml
        - docker-compose.frontend.yml
        - docker-compose.production.yml
  needs:
    - job: "pre_build:frontend:packages"
      optional: true

build:nginx:
  stage: build
  script:
    - TAG=${CI_COMMIT_REF_SLUG} docker compose -f docker-compose.yml -f docker-compose.production.yml pull nginx || true
    - TAG=${CI_COMMIT_SHA} CACHE_FROM_TAG=${CI_COMMIT_REF_SLUG} docker compose -f docker-compose.yml -f docker-compose.production.yml build nginx
    - TAG=${CI_COMMIT_SHA} docker compose -f docker-compose.yml -f docker-compose.production.yml push nginx
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/
      changes:
        - nginx/**/*
        - gitlab/build.yml
        - .gitlab-ci.yml
        - docker-compose.yml
        - docker-compose.production.yml

build:db:
  stage: build
  script:
    - TAG=${CI_COMMIT_REF_SLUG} docker compose -f docker-compose.yml -f docker-compose.production.yml pull db || true
    - TAG=${CI_COMMIT_SHA} CACHE_FROM_TAG=${CI_COMMIT_REF_SLUG} docker compose -f docker-compose.yml -f docker-compose.production.yml build db
    - TAG=${CI_COMMIT_SHA} docker compose -f docker-compose.yml -f docker-compose.production.yml push db
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/
      changes:
        - db/**/*

build:flower:
  stage: build
  script:
    - TAG=${CI_COMMIT_REF_SLUG} docker compose -f docker-compose.yml -f docker-compose.production.yml pull flower || true
    - TAG=${CI_COMMIT_SHA} CACHE_FROM_TAG=${CI_COMMIT_REF_SLUG} docker compose -f docker-compose.yml -f docker-compose.production.yml build flower
    - TAG=${CI_COMMIT_SHA} docker compose -f docker-compose.yml -f docker-compose.production.yml push flower
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/
      changes:
        - flower/**/*
        - gitlab/build.yml
        - .gitlab-ci.yml
        - docker-compose.yml
        - docker-compose.production.yml


build:imgproxy:
  stage: build
  script:
    - TAG=${CI_COMMIT_REF_SLUG} docker compose -f docker-compose.yml -f docker-compose.production.yml pull imgproxy || true
    - TAG=${CI_COMMIT_SHA} CACHE_FROM_TAG=${CI_COMMIT_REF_SLUG} docker compose -f docker-compose.yml -f docker-compose.production.yml build imgproxy
    - TAG=${CI_COMMIT_SHA} docker compose -f docker-compose.yml -f docker-compose.production.yml push imgproxy
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/
      changes:
        - imgproxy/**/*
        - gitlab/build.yml
        - .gitlab-ci.yml
        - docker-compose.yml
        - docker-compose.production.yml
