name: workflow

on:
  push:
    branches:
      - master
      - develop
      - stage

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: deploy
        run: docker compose -f docker-compose.yml -f docker-compose.${{ github.ref_name }}.yml -f docker-compose.frontend.yml up --build --remove-orphans -d
        env:
          BRANCH_NAME: ${{ github.ref_name }}