name: workflow

on:
  push:
    branches:
      - master
      - develop
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build frontend
        run:  docker compose -f docker-compose.yml -f docker-compose.frontend.yml build frontend
        env:
          BRANCH_NAME: ${{ github.ref_name }}
      - name: build backend
        run:  docker compose -f docker-compose.yml -f docker-compose.production.yml build backend
        env:
          BRANCH_NAME: ${{ github.ref_name }}
      - name: build nginx
        run:  docker compose -f docker-compose.yml -f docker-compose.production.yml build nginx
        env:
          BRANCH_NAME: ${{ github.ref_name }}

  deploy:
    needs: ["build"]
    runs-on: self-hosted
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: deploy
        run: docker compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.frontend.yml up --build --remove-orphans -d
        env:
          BRANCH_NAME: ${{ github.ref_name }}